#! /usr/bin/env bash

export DATANODE_HOST="${1:-$(hostname -i 2>/dev/null || hostname)}"

function error() {
    echo "[ERROR] $@" >&2
    return 1
}

function dos2unix() {
    local path=${1}

    [ -r "${path}" ] && 
        sed -i 's,\r$,,' ${path} || 
        error "No '${path}' found available to read"
}

function unixify() {
    for file_path in $(ls ./bin/*); do
        dos2unix "$file_path" || return 1
    done
}

function execify() {
    chmod -R 777 ./bin
}

export MSYS_NO_PATHCONV=1

unixify &&
    execify &&
    docker compose down -v &&
    docker compose up --build --remove-orphans
